name: Build Project

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3.5.2
    - name: Set up JDK 17
      uses: actions/setup-java@v3.11.0
      with:
        java-version: '17.0.7'
        distribution: 'corretto'
    - name: Grant execute permission for gradlew
      run: powershell -command "Set-ExecutionPolicy -ExecutionPolicy Bypass -Scope Process"
    - name: Build with Gradle
      run: .\gradlew build
    - name: Upload Artifact
      uses: actions/upload-artifact@v3.1.2
      with:
        name: compiled
        path: build/libs/*.jar
